### ISSUE TITLE
Aspect ratio of video player isn't correct

### ISSUE THREAD

**Issue by shaharmor** [videojs/videojs-contrib-hls#305]
Hi,

There seems to be a bug in the aspect ratio of the flash player on a live video i'm playing.
You can reproduce the issue by going to the example page: http://videojs.github.io/videojs-contrib-hls/

and then changing the source of the video by running the following snippet at the console:
```javascript
player.src([{
    type: 'application/x-mpegURL',
    src: 'https://livestream.peer5.com/video/surf-drone/index.m3u8'
}]);
```

Try that a few times and you will see that the video isn't stretching some times for the full width of the player.

How it looks:
![screen shot 2015-06-15 at 11 44 02 am](https://cloud.githubusercontent.com/assets/10861920/8156222/dc301b08-1353-11e5-98b9-8ea83df08f35.png)

How it should look:
![screen shot 2015-06-15 at 11 44 40 am](https://cloud.githubusercontent.com/assets/10861920/8156230/eedece20-1353-11e5-8c2a-dc54be95443a.png)

**Comment by dmlap** [comment]
That squished aspect ratio is the default for the Flash runtime when it is missing video dimension information. We've seen this in the past when videos segments don't begin with a keyframe or equivalent frame metadata (technically, we're looking for an SPS in the H264 data). What encoder are you using to create your stream?

**Comment by shaharmor** [comment]
This specific video is a VOD stream that i'm playing in a loop. It was generated using Kaltura server

**Comment by mgreer** [comment]
I've seen this too, it is intermittent. Since the files are statically served, and thus unchanging, it likely isn't missing a keyframe at the start on some calls and not on others.

**Comment by dmlap** [comment]
I'm working to put together a new release of videojs-swf with @qpSHiNqp's change to fix this.

**Comment by parrfolio** [comment]
Would love to get this fix.

**Comment by dmlap** [comment]
@parrfolio it should be fixed with [video.js v4.12.10](https://github.com/videojs/video.js/releases/tag/v4.12.10) which uses [video-js-swf v4.7.1](https://github.com/videojs/video-js-swf/releases/tag/v4.7.1).

**Comment by scramatte** [comment]
I still got the issue with  Firefox 39.0 on Mac with OS X Yosemite.
Chrome and safari   are Ok.

http://iptv.nicos.es/hlsbug/

**Comment by scramatte** [comment]
It seems that the issue still occurs on Mac. On Windows it looks OK.

**Comment by Awais-cb** [comment]
I am facing this issue today.on windows on latest chrome is there anyone who could help me about it.

**Comment by troyanskiy** [comment]
Hello @Awais-cb 
I'm facing the same issue. Did you found a solution?
